lenovo/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from poll.views import groups_view, users_view
from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('savollar/', include('poll.urls', namespace='poll')),
    path('', home, name="home"),
    path('accounts/', include('userprofile.urls', namespace='userprofile')),
    path("news/", include('new.urls', namespace='new')),
    path("gallery/", include('gallery.urls', namespace='gallery')),
    # path('groups/', groups_view, name="groups"),
    # path('', users_view, name="users"),
    # path('update-')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new/urls.py
from django.urls import path

from .views import news_list, news_detail, create, remove,  my_news, my_create, like, dislike

app_name = "new"
urlpatterns = [
    path('', news_list, name="list"),
    path('detail/<int:id>/', news_detail, name="detail"),
    path('yaratish/', create, name="create"),
    path('remove/<int:id>/', remove, name="remove"),
    path('my-news/', my_news, name="my_news"),
    path('my-create/', my_create, name="my_create"),
    path('like/<int:id>/', like, name="like"),
    path('dislike/<int:id>/', dislike, name="dislike"),
]

poll/urls.py
from django.urls import path

from .views import delete_question, savollar, savol_detail, check_answer, create_question, groups_view, users_view, create_choice

app_name = 'poll'
urlpatterns = [
    path('users/', users_view, name="users"),
    path('groups/', groups_view, name="groups"),
    path('savollar/', savollar, name="savollar"),
    path('savol/<int:id>/', savol_detail, name="savol"),
    path('check/<int:variant_id>/', check_answer, name="check_answer"),
    path('create-question/', create_question, name="create"),
    path('delete-question/<int:id>/', delete_question, name="delete_question"),
    path('tanlov-yaratish/', create_choice, name="create_choice"),
    
    # path('delete-group/<int:id>/', delete_group, name="delete_group"),
    # path('create-choice/', create_choice, name="create_choice"),
    # path('create-group/', create_group, name="create_group")
]

poll/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question = models.CharField("Savol", max_length=255)

    def __str__(self):
        return self.question


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField("Variant", max_length=255)
    is_correct = models.BooleanField("To'g'ri", default=False)

    def __str__(self):
        return self.choice

templates/question/checked.html
{% extends 'base.html' %}

{% block content %}

{% if correct %}
<h1>To'g'ri javob berdingiz!</h1>
{% else %}
<h1>Noto'g'ri javob berdingiz!</h1>
{% endif %}

{% endblock content %}

templates/question/create_choice.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<h1>Tanlov qo'shish: {{ savol.question }}</h1>


<form action="." method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" class="btn btn-outline-info mt-2" value="Saqlash">
</form>


{% endblock content %}

templates/question/create_question.html
{% extends 'base.html' %}

{% block content %}

<h1>Savol qo'shish:</h1>

<form action="." method="post">
    {% csrf_token %}
    <input type="text" name="question" required>
    <input type="submit" name="Saqlash">
</form>


{% endblock content %}

templates/question/savol.html
{% extends 'base.html' %}

{% block content %}

<h1>SAVOL: {{ savol.question }}</h1>

<ul class="choice">
    {% for choice in savol.choice_set.all %}
    <li><a href="{% url 'poll:check_answer' variant_id=choice.id %}">{{ choice.choice }}</a></li>
    {% endfor %}
</ul>

<a href="{% url 'poll:create_choice' %}"><div class="btn btn-outline-primary">Variant qo'shish</div></a>

<a href="{% url 'poll:delete_question' id=savol.id %}"><div class="btn btn-outline-danger">Savolni o'chirish</div></a>

{% endblock content %}

templates/question/savollar.html
{% extends 'base.html' %}

{% block content %}

<h1>Savollar</h1>

<ol>
    {% for savol in savollar %}
    <li><a href="{% url 'poll:savol' id=savol.id %}">{{ savol.question }}</a></li>
    {% endfor %}
</ol>

<a href="{% url 'poll:create_choice' %}" class="btn btn-info">Tanlov qo'shish</a>
<a href="{% url 'poll:create' %}" class="btn btn-outline-info">Qo'shish</a>

{% endblock content %}