lenovo/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from poll.views import groups_view, users_view
from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('savollar/', include('poll.urls', namespace='poll')),
    path('', home, name="home"),
    path('accounts/', include('userprofile.urls', namespace='userprofile')),
    path("news/", include('new.urls', namespace='new')),
    path("gallery/", include('gallery.urls', namespace='gallery')),
    # path('groups/', groups_view, name="groups"),
    # path('', users_view, name="users"),
    # path('update-')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new/urls.py
from django.urls import path

from .views import news_list, news_detail, create, remove,  my_news, my_create, like, dislike

app_name = "new"
urlpatterns = [
    path('', news_list, name="list"),
    path('detail/<int:id>/', news_detail, name="detail"),
    path('yaratish/', create, name="create"),
    path('remove/<int:id>/', remove, name="remove"),
    path('my-news/', my_news, name="my_news"),
    path('my-create/', my_create, name="my_create"),
    path('like/<int:id>/', like, name="like"),
    path('dislike/<int:id>/', dislike, name="dislike"),
]

templates/pages/home.html
{% extends 'base.html' %}

{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      {% for item in carousel %}
      <div class="carousel-item active">
        <img src="{{ item.image.url }}" class="d-block w-100" alt="{{ item.title }}">
      </div>
      {% endfor %}
      
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="row">
    <h1 class="my-5">Yangiliklar</h1>
  {% for new in news %}
  <div class="col-md-4">
    
    <div class="card my-5">
        {% if new.image %}
        <img src="{{ new.image.url }}" class="card-img-top" alt="{{ new.title }}">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ new.title }}</h5>
          <p class="card-text">{{ new.body|truncatewords_html:10 }}</p>
          <a href="{% url 'new:detail' id=new.id %}" class="btn btn-primary">Batafsil</a>
        </div>
    </div>
    
  </div>
  {% endfor %}
</div>

{% endblock content %}