gallery/urls.py
from django.urls import path
from .views import gallery_view

app_name="gallery"
urlpatterns = [
    path('', gallery_view, name="gallery_view"),
]

lenovo/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from poll.views import groups_view, users_view
from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('savollar/', include('poll.urls', namespace='poll')),
    path('', home, name="home"),
    path('accounts/', include('userprofile.urls', namespace='userprofile')),
    path("news/", include('new.urls', namespace='new')),
    path("gallery/", include('gallery.urls', namespace='gallery')),
    # path('groups/', groups_view, name="groups"),
    # path('', users_view, name="users"),
    # path('update-')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new/urls.py
from django.urls import path

from .views import news_list, news_detail, create, remove,  my_news, my_create, like, dislike

app_name = "new"
urlpatterns = [
    path('', news_list, name="list"),
    path('detail/<int:id>/', news_detail, name="detail"),
    path('yaratish/', create, name="create"),
    path('remove/<int:id>/', remove, name="remove"),
    path('my-news/', my_news, name="my_news"),
    path('my-create/', my_create, name="my_create"),
    path('like/<int:id>/', like, name="like"),
    path('dislike/<int:id>/', dislike, name="dislike"),
]

poll/urls.py
from django.urls import path

from .views import delete_question, savollar, savol_detail, check_answer, create_question, groups_view, users_view, create_choice

app_name = 'poll'
urlpatterns = [
    path('users/', users_view, name="users"),
    path('groups/', groups_view, name="groups"),
    path('savollar/', savollar, name="savollar"),
    path('savol/<int:id>/', savol_detail, name="savol"),
    path('check/<int:variant_id>/', check_answer, name="check_answer"),
    path('create-question/', create_question, name="create"),
    path('delete-question/<int:id>/', delete_question, name="delete_question"),
    path('tanlov-yaratish/', create_choice, name="create_choice"),
    
    # path('delete-group/<int:id>/', delete_group, name="delete_group"),
    # path('create-choice/', create_choice, name="create_choice"),
    # path('create-group/', create_group, name="create_group")
]

userprofile/urls.py
from django.urls import path
from .views import logout_view, register, login_view, profile

app_name="userprofile"
urlpatterns = [
    path('register/', register, name="register"),
    path('login/', login_view, name="login"),
    path('profile/', profile, name="profile"),
    path('logout/', logout_view, name="logout"),    
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/lightgallery.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class = "container">
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" href="{% url 'home' %}">HOME</a>
                    {% if user.is_superuser %}
                    <a class="nav-link" href="{% url 'poll:users' %}">Users</a>
                    <a class="nav-link" href="{% url 'poll:groups' %}">Groups</a>
                    {% endif %}
                    <a class="nav-link" href="{% url 'poll:savollar' %}">Questions</a>
                    <a class="nav-link" href="{% url 'new:list' %}">News</a>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'new:my_news' %}">My News</a>
                    {% comment %} {% if user == "Anonymous" %} {% endcomment %}
                    {% endif %}
                    <a class="nav-link" href="{% url 'gallery:gallery_view' %}">Gallery</a>
                    
                    
                </div>
                
            </div>
            <div class="navbar-nav float-end">
                {% if user.is_authenticated %}
                <a class="nav-link active" href="#">{{ request.user.username }}</a>
                {% endif %}
                {% if not user.is_authenticated %}
                <a class="nav-link" href="{% url 'userprofile:login' %}">Login</a>
                {% endif %}
                <a class="nav-link" href="{% url 'userprofile:register' %}">Register</a>
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'userprofile:logout' %}">Logout</a>
                {% endif %}
            </div>
            
        </div>
    </nav>
    <div class="container my-5">         
        <!-- bu ko'rinishdagi istalgan templatedagi -->
        <!-- yozuv, django template tag deyiladi -->
        {% if messages %}
        <ul class="messages" style="list-style-type: none;">
            {% for message in messages %}
            <li {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% block content %}

        {% endblock content %}
    </div>
    <script src="{% static 'js/bootstrap.jquery.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/picturefill/2.3.1/picturefill.min.js"></script>
    <script src="https://cdn.rawgit.com/sachinchoolur/lightgallery.js/master/dist/js/lightgallery.js"></script>
    <script src="https://cdn.rawgit.com/sachinchoolur/lg-pager.js/master/dist/lg-pager.js"></script>
    <script src="https://cdn.rawgit.com/sachinchoolur/lg-autoplay.js/master/dist/lg-autoplay.js"></script>
    <script src="https://cdn.rawgit.com/sachinchoolur/lg-fullscreen.js/master/dist/lg-fullscreen.js"></script>
    <script src="https://cdn.rawgit.com/sachinchoolur/lg-zoom.js/master/dist/lg-zoom.js"></script>
    <script src="https://cdn.rawgit.com/sachinchoolur/lg-hash.js/master/dist/lg-hash.js"></script>
    <script src="https://cdn.rawgit.com/sachinchoolur/lg-share.js/master/dist/lg-share.js"></script>
    <script src="{% static 'js/lg-rotate.js' %}"></script>
    <script>
        lightGallery(document.getElementById('lightgallery'));
    </script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>