lenovo/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from poll.views import groups_view, users_view
from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('savollar/', include('poll.urls', namespace='poll')),
    path('', home, name="home"),
    path('accounts/', include('userprofile.urls', namespace='userprofile')),
    path("news/", include('new.urls', namespace='new')),
    path("gallery/", include('gallery.urls', namespace='gallery')),
    # path('groups/', groups_view, name="groups"),
    # path('', users_view, name="users"),
    # path('update-')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new/urls.py
from django.urls import path

from .views import news_list, news_detail, create, remove,  my_news, my_create, like, dislike

app_name = "new"
urlpatterns = [
    path('', news_list, name="list"),
    path('detail/<int:id>/', news_detail, name="detail"),
    path('yaratish/', create, name="create"),
    path('remove/<int:id>/', remove, name="remove"),
    path('my-news/', my_news, name="my_news"),
    path('my-create/', my_create, name="my_create"),
    path('like/<int:id>/', like, name="like"),
    path('dislike/<int:id>/', dislike, name="dislike"),
]

new/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class New(models.Model):
    author = models.ForeignKey(
        User, 
        verbose_name="Muallif", 
        on_delete=models.SET_NULL, 
        null=True, blank=True
        )
    title = models.CharField("Sarlavha", max_length=255)
    body = models.TextField("Asosiy qism")
    image = models.ImageField("Rasm", upload_to = "news/", blank=True, null=True)
    created = models.DateTimeField("Sana", auto_now=True)


    class Meta:
        verbose_name = "yangilik"
        verbose_name_plural = "yangiliklar"

    def __str__(self):
        return self.title

class Comment(models.Model):
    author = models.ForeignKey(
        User, 
        verbose_name="Muallif",
        on_delete=models.SET_NULL,
        null=True,
        blank=True)
    post = models.ForeignKey(
        New,
        verbose_name="Post",
        on_delete=models.SET_NULL,
        related_name="comments",
        null=True,
        blank=True
    )
    body = models.TextField("Izoh")

    date = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.body[:20]}..."

    class Meta:
        verbose_name = "Izoh",
        verbose_name_plural = "Izohlar"


class Like(models.Model):
    post = models.ForeignKey(
        New,
        verbose_name="Post",
        on_delete=models.SET_NULL,
        related_name="likes",
        null=True,
        blank=True
    )
    user = models.ForeignKey(
        User,
        verbose_name="Muallif",
        on_delete=models.SET_NULL,
        related_name="likes",
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.user.username} likes {self.post.title}"


class Dislike(models.Model):
    post = models.ForeignKey(
        New,
        verbose_name="Post",
        on_delete=models.SET_NULL,
        related_name="dislikes",
        null=True,
        blank=True
    )
    user = models.ForeignKey(
        User,
        verbose_name="Muallif",
        on_delete=models.SET_NULL,
        related_name="dislikes",
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.user.username} dislikes {self.post.title}"

new/forms.py
from django import forms
from .models import New, Comment

class NewForm(forms.ModelForm):
    class Meta:
        model = New
        exclude = ['created']


class NewFormMine(forms.ModelForm):
    class Meta:
        model = New
        exclude = ['author', 'created']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

new/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
from django.views.generic import ListView
from .models import New, Comment, Like, Dislike
from .forms import NewForm, NewFormMine, CommentForm


class News(ListView):
    queryset = New.objects.all().order_by('-created')
    template_name = 'new/news_list.html'
    paginate_by: int = 3

    def get(self, *args, **kwargs):
        return super().get(*args,**kwargs)

news_list = News.as_view()

# def news_list(request):
#     news = New.objects.all().order_by('-created')
#     return render(request, 'new/news_list.html', {'news': news})


def news_detail(request, id):
    new = get_object_or_404(New, id=id)
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = new
            if request.user.is_authenticated:
                comment.author = request.user
            comment.save()
            return redirect("new:detail", id=id)
    return render(request, 'new/news_detail.html', {'new': new, 'form': form})

def create(request):
    form = NewForm()
    if request.method == "POST":
        form = NewForm(request.POST, request.FILES)
        if form.is_valid:
            new = form.save()
            return redirect("new:list")
    return render(request, 'new/create.html', {"form": form})

def remove(request, id):
    new = get_object_or_404(New, id=id)
    new.delete()
    return redirect("new:list")


def my_news(request,):
    news = New.objects.filter(author=request.user).order_by('-created')
    return render(request, 'new/my_news.html', {'news':news})


def my_create(request):
    form = NewFormMine()
    if request.method == "POST":
        form = NewFormMine(request.POST, request.FILES)
        if form.is_valid:
            new = form.save(commit=False)
            new.author = request.user
            new.save()
            return redirect("new:my_news")
    return render(request, 'new/create.html', {"form": form})


def like(request, id):
    new = get_object_or_404(New, id=id)
  
    if request.user.is_authenticated:
        if new.dislikes.filter(user=request.user).exists():
            new.dislikes.get(user=request.user).delete()

        if new.likes.filter(user=request.user).exists():
            new.likes.get(user=request.user).delete()
            return JsonResponse({
                "success": True,
                "message": "Siz reaksiyangizni qaytarib oldingiz!",
                "likes": new.like_count(),
                "dislikes": new.dislike_count()
                }
            )

        Like.objects.create(user=request.user, post=new)
        return JsonResponse({
                "success": True,
                "message": "Sizga yoqgan postlar safiga qo'shildi!",
                "likes": new.like_count(),
                "dislikes": new.dislike_count()
                }
            )

    return JsonResponse({
            "success": False,
            "message": "Postga reaksiya bildirish uchun iltimos ro'yhatdan o'ting!",
            }
        )

# request -> so'rov -> zapros
def dislike(request, id):
    new = get_object_or_404(New, id=id)
    if request.user.is_authenticated:
        if new.likes.filter(user=request.user).exists():
            new.likes.get(user=request.user).delete()

        if new.dislikes.filter(user=request.user).exists():
            new.dislikes.get(user=request.user).delete()
            return JsonResponse({
                "success": True,
                "message": "Siz reaksiyangizni qaytarib oldingiz!",
                "likes": new.like_count(),
                "dislikes": new.dislike_count()
                }
            )

        Dislike.objects.create(user=request.user, post=new)
        return JsonResponse({
                "success": True,
                "message": "Sizga yoqmagan postlar safiga qo'shildi!",
                "likes": new.like_count(),
                "dislikes": new.dislike_count()
                }
            )

    return JsonResponse({
            "success": False,
            "message": "Postga reaksiya bildirish uchun iltimos ro'yhatdan o'ting!",
            }
        )

templates/new/create.html
{% extends 'base.html' %}

{% load static crispy_forms_tags %}

{% block content %}

<div class="my-5">
  <h1>Yangi post yaratish</h1>
</div>

<div class="card p-5">
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-4 float-end">Yaratish</button>
    </form>    
</div>

{% endblock content %}

templates/new/my_news.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <h1 class="my-5">Yangiliklar 
      <small><a href="{% url 'new:create' %}" class="btn btn-primary float-end">Qo'shish</a></small>
    </h1>
  {% for new in object_list %}
  <div class="col-md-4">
    
    <div class="card my-5">
        {% if new.image %}
        <img src="{{ new.image.url }}" class="card-img-top" alt="{{ new.title }}">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ new.title }}</h5>
          <p class="card-text">{{ new.body|truncatewords_html:10 }}</p>
          <a href="{% url 'new:detail' id=new.id %}" class="btn btn-primary">Batafsil</a>
          <a href="{% url 'new:remove' id=new.id %}" class="btn btn-primary">Batafsil</a>
          <a href="{% url 'new:detail' id=new.id %}" class="btn btn-primary">Batafsil</a>
        </div>
    </div>
    
  </div>
  {% endfor %}
</div>


{% endblock content %}

templates/new/news_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="my-5">
  <h1>{{ new.title }}</h1>
</div>

<div class="card p-5">
    <img src="{{ new.image.url }}" class="card-img-top" alt="{{ new.title }}">
    <div class="card-body">
      <h5 class="card-title">{{ new.title }}</h5>
      <p class="card-text">{{ new.body|safe }}</p>
      <span class="small badge badge-info bg-primary">{{ new.created }}</span>
      {% if user.is_authenticated %}
      <a href="{% url 'new:remove' id=new.id %}" class="btn btn-danger float-end">O'chirish</a>
      {% endif %}
    </div>

    <hr>

    <div class="card">
      <div id="warning">
        
      </div>
      <div id="success">
        
      </div>
      <div class="card-header d-flex justify-content-center">
        <div class="d-flex align-items-center">
          <span class="fa fa-thumbs-up fa-2x d-block" id="like" data-url="{% url 'new:like' id=new.id %}"></span>
          <span class="mx-2" id="like-count">{{ new.like_count|default:0 }}</span>
        </div>
        <div class="d-flex align-items-center mx-4">
          <span class="fa fa-thumbs-down fa-2x d-block" id="dislike" data-url="{% url 'new:dislike' id=new.id %}"></span>
          <span class="mx-2" id="dislike-count">{{ new.dislike_count|default:0 }}</span>
        </div>
      </div>
    </div>

    <hr>

    <h3 class="my-3">Izohlar</h3>

    <div class="card mt-4">
      <div class="card-header">
        Izoh qoldiring!
      </div>
      <div class="card-body">
        <form action="." method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" class="btn btn-outline-success mt-3 float-end" value="Yuborish">
        </form>
      </div>
    </div>

    {% for comment in new.comments.all %}
    <div class="card mt-4">
      <div class="card-header">
        {{ comment.author|default:"Anonim foydalanuvchi" }}
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p>{{ comment.body }}</p>
          <footer class="blockquote-footer">{{ comment.date|date:"d.m.Y" }}</footer>
        </blockquote>
      </div>
    </div>
    {% endfor %}

  </div>

{% endblock content %}

templates/new/news_list.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <h1 class="my-5">Yangiliklar 
      {% if user.is_authenticated %}
      <small><a href="{% url 'new:create' %}" class="btn btn-primary float-end">Qo'shish</a></small>
      {% endif %}
    </h1>
  {% for new in object_list %}
  <div class="col-md-4">
    
    <div class="card my-5">
        {% if new.image %}
        <img src="{{ new.image.url }}" class="card-img-top" alt="{{ new.title }}">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ new.title }}</h5>
          <p class="card-text">{{ new.body|truncatewords_html:10 }}</p>
          <a href="{% url 'new:detail' id=new.id %}" class="btn btn-primary">Batafsil</a>
        </div>
    </div>
    
  </div>
  {% endfor %}
</div>

{% comment %} {% for contact in page_obj %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.full_name|upper }}<br>
    ...
{% endfor %} {% endcomment %}

<nav aria-label="Page navigation example">
  <ul class="pagination">
  
    <li class="page-item">
        <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}">
          <i class="fa fa-arrow-left"></i>
        </a>
    </li>

    {% for page in page_obj.paginator %}
    <li class="page-item">
      <a class = "page-link" href="?page={{ page.number }}">{{ page.number }}</a>
    </li>
    {% endfor %}

    <li class="page-item">    
      <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}">
        <i class="fa fa-arrow-right"></i>        
      </a>     
    </li>
  </ul>
</nav>

{% endblock content %}